# Generated by Django 6.0.2 on 2026-03-23 09:57

import apps.projects.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_public_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='public_id',
            field=models.CharField(default=apps.projects.models.generate_public_id, editable=False, max_length=20, null=True),
        ),
    ]
