# Generated by Django 6.0.2 on 2026-03-23 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_project_public_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='public_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
