# Generated by Django 6.0.2 on 2026-03-23 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_project_public_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='public_id',
        ),
    ]
