# Generated by Django 6.0.2 on 2026-03-23 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_remove_project_public_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='public_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
