# Generated by Django 6.0.2 on 2026-03-23 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_project_public_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='public_id',
            field=models.CharField(editable=False, max_length=20, unique=True),
        ),
    ]
