# Generated by Django 6.0.2 on 2026-03-05 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_deleted_at_task_is_delete'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='is_delete',
            new_name='is_deleted',
        ),
    ]
