# Generated by Django 6.0.2 on 2026-03-23 15:02

import django.contrib.postgres.indexes
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_project_projects_pr_search__1d35f9_gin'),
        ('tasks', '0006_task_search_vector'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='task',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='tasks_task_search__21079e_gin'),
        ),
    ]
